### ISSUE TITLE
Doesn't show any notifications and wont play

### ISSUE THREAD

**Issue by vsfarooqkhan** [pylerSM/YouTubeBackgroundPlayback#287]
I installed YouTube background play and enabled it in xposed installer. After rebooting my phone, i opened YouTube and minimised it, but won't play background video... Even i can't see any notification in my status bar. Please help me

**Comment by Kronopt** [comment]
Go to Xposed app.
Download section.
Enter YouTubeBackgroundPlayback.
Go to settings.
Set "versions to be shown" to experimental.
Install latest version (2.0.1)

**Comment by vsfarooqkhan** [comment]
After did the following steps, Still the same error occurs... I cant see
any notification on my phone , after reboot my mobile was still shows any
notification..
Please help me

**Comment by Kronopt** [comment]
Then I suggest you wait.
The youtube app was recently updated, and the developers might not have had the time to fix YouTubeBackgroundPlayback.

**Comment by vsfarooqkhan** [comment]
Ah thank you for your support.
Now it works well.
Thank you.
Wonderful app.

**Comment by th3an7** [comment]
@Kronopt Sources have been updated - module should work now for YT 11.47.57... just wait a second till new raw .json file will be available (shouldn't take long) and restart updated app (kill it or swipe from recents) :)

**Comment by Asikaani** [comment]
Im still having issue with YT 11.47.57 and 2.0.1 Module. Doesn't play background and there is no notification.

**Comment by Asikaani** [comment]
Ok no problem anymore. Had to install 2.0.0 before updating 2.0.1 so everything works great now! :)
